# most use variables
declare -lA paths
paths[sdk]="$HOME/.local/sdk"
paths[data]="$HOME/.local/share"
paths[config]="$HOME/.config"
paths[cache]="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export EDITOR=nano
export VISUAL=nano

# for zsh self
export ZDOTDIR="$paths[config]/zsh"
export HISTFILE="$XDG_STATE_HOME/zsh_history"
export CLICOLOR=true
export LSCOLORS="exfxcxdxbxegedabagacad"

# for utils
export HOMEBREW_PREFIX="/opt/homebrew"
export HOMEBREW_CELLAR="$HOMEBREW_PREFIX/Cellar"
export HOMEBREW_REPOSITORY="$HOMEBREW_PREFIX"
export MANPATH="/usr/share/man:/usr/local/share/man"
export MANPATH="$MANPATH:$HOMEBREW_PREFIX/share/man"
export INFOPATH="/usr/share/info:/usr/local/share/info"
export INFOPATH="$INFOPATH:$HOMEBREW_PREFIX/share/info"

# for less
export LESSKEY="$paths[config]/less/lesskey"
export LESSHISTFILE="$XDG_STATE_HOME/less_history"

# for sql
export SQLITE_HISTORY="$XDG_STATE_HOME/sqlite_history"
export PSQLRC="$paths[config]/psqlrc"
export PSQL_HISTORY="$XDG_STATE_HOME/psql_history"
export PGPASSFILE="$XDG_CONFIG_HOME/postgres/pgpass"
export PGSERVICEFILE="$XDG_CONFIG_HOME/postgres/pg_service.conf"
export MYSQL_HISTFILE="$XDG_STATE_HOME/mysql_history"

# for nodejs
export NPM_CONFIG_USERCONFIG="$paths[config]/npm/npmrc"
export NODE_REPL_HISTORY="$XDG_STATE_HOME/npm_history"
export NODE_PATH="/opt/homebrew/lib/node_modules:$paths[data]/npm/lib/node_modules/"

# for rust
export RUSTUP_BIN="$HOMEBREW_PREFIX/opt/rustup/bin" # homebrew only
export RUSTUP_HOME="$paths[sdk]/rustup"
export CARGO_HOME="$paths[sdk]/cargo"
export RUST_BACKTRACE=full

# for haskell
export integer STACK_XDG=1
export integer GHCUP_USE_XDG_DIRS=1
export CABAL_DIR="$paths[data]/cabal"
export CABAL_CONFIG="$paths[config]/cabal/config"
export AGDA_DIR="$paths[sdk]/agda"

# for python
export JUPYTER_DATA_DIR="$paths[config]/jupyter"
export IPYTHONDIR="$JUPYTER_DATA_DIR"
export JUPYTER_CONFIG_DIR="$JUPYTER_DATA_DIR"
export PYTHONSTARTUP="$paths[config]/pip/startup.py"
export MPLCONFIGDIR="$XDG_STATE_HOME/matplotlib"

#? rye
export RYE_HOME="$paths[sdk]/rye"
#? latex
export TEXMFHOME="$paths[data]/texmf"
export TEXMFVAR="$paths[cache]/texlive/texmf-var"
export TEXMFCONFIG="$paths[config]/texlive/texmf-config"
#? ocaml
export OPAMROOT="$paths[sdk]/opam"
#? wolfram
export WOLFRAM_USERBASE="$XDG_STATE_HOME/wolfram"
#? go
export GOPATH="$paths[sdk]/go"
export GO111MODULE="on"
export GOPROXY="https://goproxy.io,direct"

# compose path
paths[homebrew]="/opt/homebrew/bin:/opt/homebrew/sbin" # for homebrew
paths[path]="$RUSTUP_BIN"                              # for rustup itself
paths[path]+=":$RUSTUP_HOME/bin"                       # for rustup
paths[path]+=":$CARGO_HOME/bin"                        # for rust cargo
paths[path]+=":$HOME/.local/bin"                       # for user local
paths[path]+=":$HOMEBREW_PREFIX/opt/postgresql@16/bin" # for postgresql
export PATH="$paths[path]":"$PATH"                     # user path before system path
