# most use variables
declare -lA lens
lens[sdk]="$HOME/.local/sdk"
lens[data]="$HOME/.local/share"
lens[config]="$HOME/.config"
lens[cache]="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export EDITOR=pico
export VISUAL=code

# for zsh self
export ZDOTDIR="$lens[config]/zsh"
export HISTFILE="$XDG_STATE_HOME/zsh_history"
export CLICOLOR=true
export LSCOLORS="exfxcxdxbxegedabagacad"

# for utils
export PSQLRC="$lens[config]/psqlrc"
export PSQL_HISTORY="$XDG_STATE_HOME/psql_history"
export HOMEBREW_PREFIX="/opt/homebrew"
export HOMEBREW_CELLAR="$HOMEBREW_PREFIX/Cellar"
export HOMEBREW_REPOSITORY="$HOMEBREW_PREFIX"
# ? mirror start
export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.ustc.edu.cn/brew.git"
export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.ustc.edu.cn/homebrew-core.git"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles"
export HOMEBREW_API_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles/api"
# ? mirror end
export MANPATH="/usr/share/man:/usr/local/share/man"
export MANPATH="$MANPATH:$HOMEBREW_PREFIX/share/man"
export INFOPATH="/usr/share/info:/usr/local/share/info"
export INFOPATH="$INFOPATH:$HOMEBREW_PREFIX/share/info"

# for nodejs
export NPM_CONFIG_USERCONFIG="$lens[config]/npm/npmrc"
export NODE_REPL_HISTORY="$XDG_STATE_HOME/npm_history"
export NODE_PATH="/opt/homebrew/lib/node_modules:$lens[data]/npm/lib/node_modules/"

# for less
export LESSKEY="$lens[config]/less/lesskey"
export LESSHISTFILE="$XDG_STATE_HOME/less_history"

# for haskell
export integer STACK_XDG=1
export integer GHCUP_USE_XDG_DIRS=1
export AGDA_DIR="$lens[sdk]/agda"

# for python
export JUPYTER_DATA_DIR="$lens[config]/jupyter"
export IPYTHONDIR="$JUPYTER_DATA_DIR"
export JUPYTER_CONFIG_DIR="$JUPYTER_DATA_DIR"
export PYTHONSTARTUP="$lens[config]/pip/pyrc"
export PYLINTHOME="$XDG_STATE_HOME/pylint"
export MPLCONFIGDIR="$lens[config]/matplotlib"

# for rust
export RUSTUP_DIST_SERVER="https://mirrors.ustc.edu.cn/rust-static"
export RUSTUP_UPDATE_ROOT="https://mirrors.ustc.edu.cn/rust-static/rustup"
export RUSTUP_BIN="$HOMEBREW_PREFIX/opt/rustup/bin"
export RUSTUP_HOME="$lens[sdk]/rustup"
export CARGO_HOME="$lens[sdk]/cargo"
export RUST_BACKTRACE=full

# compose path
lens[homebrew]="/opt/homebrew/bin:/opt/homebrew/sbin" # for homebrew
lens[path]="$RUSTUP_BIN"                              # for rustup itself
lens[path]+=":$RUSTUP_HOME/bin"                       # for rustup
lens[path]+=":$CARGO_HOME/bin"                        # for rust cargo
lens[path]+=":$HOME/.local/bin"                       # for user local
export PATH="$lens[path]":"$PATH"                     # user path before system path
