#!/usr/bin/env bash

# path
allPath="$HOME/.local/bin"               # user bin
allPath+=":$HOME/.local/share/npm/bin"   # node
allPath+=":$HOME/.local/share/cabal/bin" # haskell
allPath+=":$HOME/.local/sdk/cargo/bin"   # rust
allPath+=":$HOME/.local/sdk/go/bin"      # golang
allPath+=":$PATH"
export PATH="$allPath"

# ghcup-env
[ -f "/home/kands/.local/share/ghcup/env" ] && source "/home/kands/.local/share/ghcup/env"

# systemd environment variables
if [[ -f "/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator" ]]; then
  export $(/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator)
fi
## use en_US.UTF-8 as tty LANG
if [[ "$XDG_SESSION_TYPE" == "tty" ]]; then
  export LANG='en_US.UTF-8'
fi
systemctl --user import-environment PATH

# read bashrc if it exists
[[ -f "$HOME/.bashrc" ]] && source "$HOME/.bashrc"
